# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "10.0.0.11"
  config.vm.synced_folder "C:/Virtual Machines/Working Environment", "/var/www/vagrant"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision :shell, path: "firstboot.sh"
  config.vm.provision :shell, path: "bootstrap.sh", run: "always"
end
